version: 2

jobs:
  build:

    macos:
      xcode: "8.3.3"

    steps:
      - checkout

      - run:
          name: Install CocoaPods
          command: pod install

      - run:
          name: Build and run tests
          command: >
            xcodebuild \
                    -workspace TreasureData.xcworkspace \
                    -scheme TreasureData \
                    -sdk iphonesimulator \
                    -destination 'platform=iOS Simulator,name=iPhone 7,OS=12.1' \
                    test
